# Datasource
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /api
