# Datasource
spring.datasource.url=jdbc:postgresql://34.142.227.217:30001/postgres
spring.datasource.username=master
spring.datasource.password=pwd

#server.error.include-binding-errors=always
#server.error.include-message=always
#server.error.include-exception=true
